import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      firstName: 'Yohannes',
      lastName: 'Habtemariam',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456789'),
      isAdmin: true,
    },
    {
      firstName: 'Lisa',
      lastName: 'Habtemariam',
      email: 'lisa@gmail.com',
      password: bcrypt.hashSync('123456789'),
      isAdmin: false,
    },
    {
      firstName: 'Tim',
      lastName: 'Habtemariam',
      email: 'tim@gmail.com',
      password: bcrypt.hashSync('123456789'),
      isAdmin: false,
    },

    {
      firstName: 'Rai',
      lastName: 'Habtemariam',
      email: 'rai@gmail.com',
      password: bcrypt.hashSync('123456789'),
      isAdmin: false,
    },
    {
      firstName: 'Yuel',
      lastName: 'Habtemariam',
      email: 'yuel@gmail.com',
      password: bcrypt.hashSync('123456789'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: 'Organic Rice',
      image: 'http://localhost:8888/meal-1.jpg',
      category: 'Vegetables',
      brand: 'Organic',
      price: 5,
      countInStock: 34,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },
    {
      // _id: "2",
      name: 'Fresh Vegetables',
      image: 'http://localhost:8888/meal-2.jpg',
      category: 'Cereals',
      brand: 'Organic',
      price: 10,
      countInStock: 6,
      rating: 4,
      description: 'high quality and healthy dish',
    },
    {
      // _id: "3",
      name: 'Mixed Meals',
      image: 'http://localhost:8888/meal-3.jpg',
      category: 'Vegetables',
      brand: 'Organic',
      price: 15,
      countInStock: 0,
      rating: 4,
      description: 'high quality and healthy dish',
    },
    {
      // _id: "4",
      name: 'Salad & Fruit',
      image: 'http://localhost:8888/meal-4.jpg',
      category: 'mixed',
      brand: 'Organic',
      price: 7,
      countInStock: 0,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },
    {
      // _id: "5",
      name: 'PVF',
      image: 'http://localhost:8888/meal-5.jpg',
      category: 'mixed',
      brand: 'Organic',
      price: 5,
      countInStock: 9,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },
    {
      // _id: "6",
      name: 'Fish',
      image: 'http://localhost:8888/meal-6.jpg',
      category: 'meat',
      brand: 'Organic',
      price: 15,
      countInStock: 9,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "7",
      name: 'Salad',
      image: 'http://localhost:8888/meal-7.jpg',
      category: 'Vegetables',
      brand: 'Organic',
      price: 5,
      countInStock: 5,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "8",
      name: 'Spagetti With Abocado',
      image: 'http://localhost:8888/meal-8.jpg',
      category: 'Mixed',
      brand: 'Organic',
      price: 8,
      countInStock: 5,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "9",
      name: 'Mised Dish',
      image: 'http://localhost:8888/meal-9.jpg',
      category: 'Mixed',
      brand: 'Organic',
      price: 9,
      countInStock: 5,
      rating: 4,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "10",
      name: 'Spiced Rice',
      image: 'http://localhost:8888/meal-10.jpg',
      category: 'Mixed',
      brand: 'Organic',
      price: 10,
      countInStock: 15,
      rating: 4,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "11",
      name: 'Vegefruit',
      image: 'http://localhost:8888/meal-11.jpg',
      category: 'Mixed',
      brand: 'Organic',
      price: 4,
      countInStock: 15,
      rating: 4,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "12",
      name: 'Sald',
      image: 'http://localhost:8888/meal-12.jpg',
      category: 'Vegetables',
      brand: 'Organic',
      price: 12,
      countInStock: 15,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "13",
      name: 'Mixed Meals',
      image: 'http://localhost:8888/meal-13.jpg',
      category: 'mixed',
      brand: 'Organic',
      price: 17,
      countInStock: 24,
      rating: 5,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "14",
      name: 'Pizza',
      image: 'http://localhost:8888/meal-14.jpg',
      category: 'pizza',
      brand: 'Organic',
      price: 6,
      countInStock: 24,
      rating: 5,
      description: 'high quality and healthy dish',
    },

    {
      // _id: "15",
      name: 'Pizza',
      image: 'http://localhost:8888/meal-15.jpg',
      category: 'pizza',
      brand: 'Organic',
      price: 6,
      countInStock: 24,
      rating: 4.5,
      description: 'high quality and healthy dish',
    },
  ],
};
export default data;
